grv2 = 0.7;
grabbed = false;
vsp2=1;
rage_timer = 30;
rage = false;
grab_free_time = 180;
hit_player = false;
hitted = false;
hit_counter=30;
shooting_timer = 120
value = 10 ;
dead=false;
fullHp = 100; 
hp = fullHp;
hp_buff=false;
damage = 1;
sound_played=false;
timeEnds=false;
better_reward = false;

entityOnMinimap = true;